version: '3.8'

services:
  mariadb:
    image: mariadb:11.5.2
    container_name: mariadb_QTRAN
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    ports:
      - "9901:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - db_network

  mysql:
    image: mysql:8.0.39
    container_name: mysql_QTRAN
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    ports:
      - "13306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - db_network

  clickhouse:
    image: clickhouse/clickhouse-server:24.9.2.42
    container_name: clickhouse_QTRAN
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    networks:
      - db_network

  monetdb:
    image: monetdb/monetdb-r-docker
    container_name: monetdb_QTRAN
    ports:
      - "50000:50000"
    volumes:
      - monetdb_data:/var/lib/monetdb
    networks:
      - db_network

  postgres:
    image: postgres:16.3
    container_name: postgres_QTRAN
    environment:
      POSTGRES_PASSWORD: "123456"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db_network

networks:
  db_network:
    driver: bridge

volumes:
  mariadb_data:
  mysql_data:
  clickhouse_data:
  monetdb_data:
  postgres_data:
